/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:04b2c894-f374-4e8e-87ac-67cf763e5296",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dVofMvSpx",
    "aws_user_pools_web_client_id": "6opdg9q694ubv2vq4kgb5utce0",
    "oauth": {}
};


export default awsmobile;
