/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:04b2c894-f374-4e8e-87ac-67cf763e5296",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dVofMvSpx",
    "aws_user_pools_web_client_id": "6opdg9q694ubv2vq4kgb5utce0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dyll3l6mdrbfhidocbz3keimku.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5d57rmpl6fallexaedbv2eqrzm"
};


export default awsmobile;
